version: "3"
services:
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    ports:
      - "19000:9000"
    volumes:
      - ./portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
2