server:
  port: 8080


spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 18080
        dashboard: localhost:8748
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: service-hi
          uri: lb://service-hi
          predicates:
            - Path=/servicehi/**
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
          filters:
            #发送到下游之前,原来路径截取前面几位 /demo/hi  ->发送到serviceHi  /hi
            - StripPrefix=1
        - id: service-feign
          uri: lb://service-feign
          predicates:
            - Path=/servicefeign/**
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
          filters:
            #发送到下游之前,原来路径截取前面几位 /demo/hi  ->发送到serviceHi  /hi
            - StripPrefix=1
