version: '3'
services:
  ftp-server:
    image: fauria/vsftpd
    ports:
      - "21:21"
    volumes:
      - ./ftp-data:/home/vsftpd
    environment:
      - FTP_USER=admin
      - FTP_PASS=admin123
      - PASV_ADDRESS=192.168.0.226
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
