server:
  port: 8765  #8765-
spring:
  application:
    name: service-feign
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 18765
        dashboard: localhost:8748


feign:
  sentinel:
    enabled: true
