server:
  port: 21883  #8762-8764

spring:
  application:
    name: service-mqtt
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 18762
        dashboard: localhost:8748


mqtt:
  #url: ssl://10.1.91.127:8885 #推送信息的连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613,tcp://192.168.1.61:61613
  url: ssl://192.168.40.131:8883
  username: wm
  password: 123
  clientId: mqttClientWm
