version: '3'
services:
  emqx:
    image: "emqx/emqx:4.4.2"
    environment:
      - EMQX_LOADED_PLUGINS="emqx_management,emqx_auth_http,emqx_dashboard"
      - EMQX_DASHBOARD__DEFAULT_USER__LOGIN=wm
      - EMQX_DASHBOARD__DEFAULT_USER__PASSWORD=wm@123
      - EMQX_NODE__MAX_PORTS=65535
      - EMQX_MQTT__MAX_PACKET_SIZE=16MB
    ports:
      - 18083:18083
      - 1883:1883
      - 8081:8081
      - 8883:8883
    volumes:
      - ./log:/opt/emqx/log
      - ./data:/opt/emqx/data
      - /etc/localtime:/etc/localtime
      - ./etc:/opt/emqx/etc
    restart: always
