version: '3'

services:

  mysql5.7:
    image: mysql:5.7
    container_name: mysql_5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --init-connect='SET NAMES utf8mb4;'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/:/var/lib/mysql
      - ./etc/mysql.conf.d/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./init:/docker-entrypoint-initdb.d/
    restart: always
    ports:
      - '3396:3306'
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: babycare
      MYSQL_USER: babycare
      MYSQL_PASSWORD: vN+lMZQiO7E=